- hosts: all
  sudo: true
  tasks:
    - yum: name=libselinux-python
    - copy: src=config/hosts dest=/etc/hosts

- hosts: zookeeper0
  sudo: true
  tasks:
    - shell: hostname zookeeper0
    - shell: /etc/init.d/network restart 

- hosts: zookeeper1
  sudo: true
  tasks:
    - shell: hostname zookeeper1
    - shell: /etc/init.d/network restart

- hosts: zookeeper2
  sudo: true
  tasks:
    - shell: hostname zookeeper2
    - shell: /etc/init.d/network restart

- hosts: hdfs0
  sudo: true
  tasks:
    - shell: hostname hdfs0
    - shell: /etc/init.d/network restart

- hosts: hdfs1
  sudo: true
  tasks:
    - shell: hostname hdfs1
    - shell: /etc/init.d/network restart

- hosts: hdfs2
  sudo: true
  tasks:
    - shell: hostname hdfs2
    - shell: /etc/init.d/network restart

- hosts: hbase0
  sudo: true
  tasks:
    - shell: hostname hbase0
    - shell: /etc/init.d/network restart

- hosts: flume0
  sudo: true
  tasks:
    - shell: hostname flume0
    - shell: /etc/init.d/network restart

- hosts: yarn0
  sudo: true
  tasks:
    - shell: hostname yarn0
    - shell: /etc/init.d/network restart

- hosts: hive0
  sudo: true
  tasks:
    - shell: hostname hive0
    - shell: /etc/init.d/network restart

- hosts: solr0
  sudo: true
  tasks:
    - shell: hostname solr0
    - shell: /etc/init.d/network restart

- hosts: spark0
  sudo: true
  tasks:
    - shell: hostname spark0
    - shell: /etc/init.d/network restart

- hosts: all
  sudo: true
  tasks:
    - get_url: url=http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/cloudera-manager.repo dest=/etc/yum.repos.d
    - yum: name=oracle-j2sdk1.7
    - yum: name=cloudera-manager-agent
    - yum: name=cloudera-manager-daemons

- hosts: cdh
  sudo: true
  tasks:
    - user: name=vagrant generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
    - fetch: src=/home/vagrant/.ssh/id_rsa.pub dest=config/ flat=yes
    - fetch: src=/home/vagrant/.ssh/id_rsa dest=config/ flat=yes
    - yum: name=cloudera-manager-server-db-2
    - yum: name=cloudera-manager-server
    - shell: service cloudera-scm-server start

- hosts: all
  sudo: true
  tasks:
    - shell: service cloudera-scm-agent start
    - authorized_key: user=vagrant key="{{ lookup('file', 'config/id_rsa.pub') }}"
    - shell: echo "vm.swappiness=0" >> /etc/sysctl.conf 
